### ISSUE TITLE
Ace3 Library Issues - Table updates?

### ISSUE THREAD

**Issue by avoidit** [fiskee/DoMeWhen-Classic#37]
Attached are the LUA errors at launch.  I am researching the issue but posting this just in case someone else has some info on it.

[lua_error1.txt](https://github.com/fiskee/DoMeWhen-Classic/files/5645922/lua_error1.txt)
[lua_error2.txt](https://github.com/fiskee/DoMeWhen-Classic/files/5645923/lua_error2.txt)
[lua_error3.txt](https://github.com/fiskee/DoMeWhen-Classic/files/5645924/lua_error3.txt)
[lua_error4.txt](https://github.com/fiskee/DoMeWhen-Classic/files/5645925/lua_error4.txt)

Message: ...DoMeWhen-Classic\Classes\LocalPlayer\LocalPlayer.lua:10: attempt to index a nil value
Time: Fri Dec  4 16:23:50 2020
Count: 1
Stack: ...DoMeWhen-Classic\Classes\LocalPlayer\LocalPlayer.lua:10: attempt to index a nil value
...DoMeWhen-Classic\Classes\LocalPlayer\LocalPlayer.lua:10: in function `New'
...nterface\AddOns\DoMeWhen-Classic\Classes\Classes.lua:12: in function `LocalPlayer'
Interface\AddOns\DoMeWhen-Classic\Core.lua:41: in function <Interface\AddOns\DoMeWhen-Classic\Core.lua:37>
Interface\AddOns\DoMeWhen-Classic\Core.lua:72: in function <Interface\AddOns\DoMeWhen-Classic\Core.lua:66>

**Comment by fiskee** [comment]
Looks to be related to class detection, seems like unlock is active before usual

**Comment by fiskee** [comment]
Someone told me this is now fixed, should be good now
